### ISSUE TITLE
Add parameters to ExpiringMap: default timeout and expiration callbacks

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#122]
The ExpiringMap class can be used as a concurrent hash map with an explicit way to handle expiration.
It would be great to have a way to set a global default timeout for any puts.
It would be good to also have expiration callbacks that execute whenever a timeout is reached.

**Comment by abbasdgr8** [comment]
Hi @atoulme 

I wouldn't mind working on this.

**Comment by atoulme** [comment]
by all means
