### ISSUE TITLE
Add javadoc and dokka docs website to Tuweni website

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#124]
We have the ability to generate javadoc and dokka docs for Apache Tuweni, but it's not been maintained.
* Look at it and make sure this works well again.
* Take the latest bin release and make it part of the website, by unzipping it and adding it to the gh-pages branch of the repo.

**Comment by sirinath** [comment]
Minimally there should be the JavaDocs but more generic tutorials are desiable.

**Comment by atoulme** [comment]
What would you like to see first?

**Comment by sirinath** [comment]
I guess java docs are the low hanging fruit. Then write some tutirials.

**Comment by atoulme** [comment]
So we have javadocs. We are going to get them published. Do you have an inclination for which tutorials to write?

**Comment by sirinath** [comment]
I think it would be good to start with some basic getting started tutorial. Also overview of the features and the basics of how they can be used.

**Comment by atoulme** [comment]
94dc05b adds dokka docs to the website, you can now consult them here: http://tuweni.apache.org/docs/

**Comment by sirinath** [comment]
That's great! Will have a look.

**Comment by atoulme** [comment]
Also added a getting started guide for bytes - http://tuweni.apache.org/tutorials/getting-started-with-bytes/

**Comment by atoulme** [comment]
Closing the issue! Let me know if you have something you'd like to see.
