### ISSUE TITLE
Create a mainnet and other ready-made blockchain information classes

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#153]
`SimpleBlockchainInformation` allows to create information about the eth subprotocol to other clients.

Use a fixed set for mainnet, goerli, rinkeby and ropsten.

**Comment by ogkunald** [comment]
Hello,I would like to work on this, can you assign this to me and can you explain where the classes needs to be added

**Comment by atoulme** [comment]
Sure thing. I think you need to look at `SimpleBlockchainInformation` first - see how some of the information there like chain id, genesis hash, network ID are fixed per network? Create a map of "network name" to this information, so it becomes easier to read this from config.
