### ISSUE TITLE
Support for libsodium >= 1.0.17 in Apache Tuweni

### ISSUE THREAD

**Issue by r-peter** [apache/incubator-tuweni#163]
Tuweni (1.2.0) has support up to Libsodium 1.0.16. Libsodium has newer versions available - 1.0.17 and higher. 
https://github.com/jedisct1/libsodium/blob/master/ChangeLog

It would be nice to have support for newer versions of Libsodium also.

Related discussion thread is here:
https://mail-archives.apache.org/mod_mbox/tuweni-users/202011.mbox/%3cCAEShzP57Eu1U7EHSmUFHk+VfoMYc2sosVxvQ7x8bMcdXFQqUkQ@mail.gmail.com%3e

**Comment by atoulme** [comment]
We generate the sodium sources by applying this python script to the sodium header file:
https://gist.github.com/atoulme/d37e62545c68dcddd389f284f779311e

**Comment by atoulme** [comment]
@r-peter do you want to take a look at the PR?

**Comment by r-peter** [comment]
Thank you so much @atoulme for incorporating the changes very quickly. The changes look good to me. I am building my solution using the SNAPSHOT I have created from your feature branch. 
I observed failure of 2 test cases on my Windows machine. I can open another issue to report it to the team as it is not related to the changes made in this branch.

**Comment by atoulme** [comment]
Please do open another issue. I don’t have a Windows dev box but we can start testing with GitHub actions if that helps.

**Comment by atoulme** [comment]
#167 fixes the Windows issue. Closing.
