### ISSUE TITLE
Move all the KeyValueStores to Infinispan

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#260]
Instead of going direct to LevelDB, use Infinispan with a default RocksDB backend - similar to what we do today for headers.

**Comment by SivaTharun** [comment]
@atoulme can i work on this issue, could you please elaborate on the use case and create sub tasks for the same.

**Comment by atoulme** [comment]
You don't need my permission at all, feel free. The code is at https://github.com/apache/incubator-tuweni/blob/38ad981697eae149bb66175099277d37564bfba9/eth-client/src/main/kotlin/org/apache/tuweni/ethclient/EthereumClient.kt#L108 Look how `InfinispanKeyValueStore` is used and replace all occurrences of `LevelDBKeyValueStore` with it.
