### ISSUE TITLE
findLargestTotalDifficulty nits

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#266]
Make the javadoc better
Don't return `Hash?`, return `Hash` instead.

**Comment by SivaTharun** [comment]
@atoulme can i work on this, can you also specify the list of classes the changes that are to be addressed to.

**Comment by atoulme** [comment]
Absolutely. The class to change is here: https://github.com/apache/incubator-tuweni/blob/257e37a1a8439197412fbc5c8e74d0fa5dcb420a/eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainIndex.kt#L148

**Comment by sudo-update** [comment]
Hi Antoine, I was looking at this and thinking of working on this.  Not sure what you would like for desired behavior if the scoreDocs is empty? Looking at the other functions, should I return List<Hash> instead?

**Comment by atoulme** [comment]
I am not sure I understand. Open a pull request for review please.
