### ISSUE TITLE
Don't bother returning more than 1 hit

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#267]
BlockchainIndex returns 10 hits, but only the first one is observed and returned. Simplify the code, return first hit only, and remove the weird for loops that returns on the first element.

**Comment by sudo-update** [comment]
Hey can I work on this?

**Comment by atoulme** [comment]
Sure thing. Send a pull request when you feel good about it.

**Comment by sudo-update** [comment]
Thank you so much.  I will start right away, but I apologize ahead of time if I need to reach out with questions.  I am new to open source contribution. Thanks again.

**Comment by atoulme** [comment]
Any help is welcome. For this one, start here:
https://github.com/apache/incubator-tuweni/blob/257e37a1a8439197412fbc5c8e74d0fa5dcb420a/eth-repository/src/main/kotlin/org/apache/tuweni/eth/repository/BlockchainIndex.kt#L763
