### ISSUE TITLE
Tuweni provides an SLF4J implementation

### ISSUE THREAD

**Issue by jflo** [apache/incubator-tuweni#344]
I had to exclude it from our dependency tree in [this PR](https://github.com/hyperledger/besu/pull/2988) since it conflicted with log4j2. It's no big deal, but perhaps there is a way to make it a provided-scope dependency instead?

**Comment by atoulme** [comment]
Currently those dependencies are provided with a runtime dependency. I'll go read more on provided vs runtime.
