### ISSUE TITLE
Improve DNSResolver log

### ISSUE THREAD

**Issue by fab-10** [apache/incubator-tuweni#370]
We are using Tuweni in [Besu](https://github.com/hyperledger/besu/), and some users find the following log line misleading

```
2022-02-22 16:44:04.285+00:00 | Timer-0 | INFO  | DNSResolver | Resolved 0 nodes
```
since they think that something went wrong with the DNS resolver, while everything is fine, since what is actually happening, is that there are no new nodes to resolve, since the sequence is not increased, looking at the debug log:
```
{"timestamp":"2022-02-22T17:47:29,325","level":"DEBUG","thread":"Timer-0","class":"DNSResolver","message":"ENR tree root seq enrtree-root:v1 e=ZPZNBATGXWZOFW33QLGJWTVHM4 l=FDXN3SN67NA5DKA4J2GOK7BVQI seq=2941 sig=6URRq9MWZL_q9W2zasLUPL21Lw7ND5LAjR-X9pEpLVtkURllhjbRAmdTNDHo20t1bOfAgf2V88Kj4xHGEjBeTAE=.seq is not higher than 2941, aborting","throwable":""}
```

A proposal to improve this log is to not log when `nodes` is empty, or when the sequence is not increased.

**Comment by atoulme** [comment]
Sounds good - please send a patch.
