### ISSUE TITLE
toShortHexString should return "0x0" for 0

### ISSUE THREAD

**Issue by siladu** [apache/incubator-tuweni#448]
I might be wrong but I believe toShortHexString contains a bug for the zero value.

It's correct according to this test case but I'm not convinced the test case is correct:
https://github.com/apache/incubator-tuweni/blob/ef737ec675997da710735e9b7acba87755f2a290/bytes/src/test/java/org/apache/tuweni/bytes/CommonBytesTests.java#L446

I would also argue that trimLeadingZeros should also return "0x0" for 0 since zero isn't a _leading_ zero.

I came across this for UInt64 but may apply to other datatypes. 

Please could I get confirmation if this is a bug or not?

**Comment by ajsutton** [comment]
It largely depends on the requirements for serialisation.  In RLP a UInt64 of 0 is actually a byte string (because RLP doesn't have numbers) so is serialised as `0x`.  In JSON-RPC Quantities trim leading zeros _except_ for the zero value so 0 is represented as `0x0`. So there's isn't really one "right" answer.

**Comment by siladu** [comment]
> In RLP a UInt64 of 0 is actually a byte string (because RLP doesn't have numbers) so is serialised as 0x

That's fair and I can see how toShortHexString might have different requirements depending on if you want to serialize to RLP or JSON.

I would still argue trimLeadingZeros is either a misleading name or behaviour. Maybe it makes sense for the RLP scenario, but it could be more explicit about it in the name as for me that was unexpected behaviour.

**Comment by siladu** [comment]
Happy to close this as a non-issue since I can use `UInt64.getBytes().toQuantityHexString()` instead. I'll leave this issue open for a couple of days in case there's further comment

**Comment by atoulme** [comment]
0x0 is not a valid hex string, it’s a bit of an oddity introduced by JSON-RPC. Trimming leading zeros means trimming zero bytes. 0x0 cannot have zero length, it will be interpreted as a byte array of length 1 containing a zero byte.

**Comment by siladu** [comment]
Thanks @atoulme I'll close this as it's clearly been considered and is intentional.
