### ISSUE TITLE
SSZ encoding of list of booleans

### ISSUE THREAD

**Issue by franck44** [apache/incubator-tuweni#49]
The encoding (serialisation) fo list of booleans seem to produce 
1. a unit32 with the size of the list
2. a sequence of Bytes each one encoding a bit in the list. 

This is according to the implementation
https://github.com/apache/incubator-tuweni/blob/03c08eeeba108670938252fef1fee209bdf435fe/ssz/src/main/java/org/apache/tuweni/ssz/SSZ.java#L1221

and test 
https://github.com/apache/incubator-tuweni/blob/03c08eeeba108670938252fef1fee209bdf435fe/ssz/src/test/java/org/apache/tuweni/ssz/BytesSSZWriterTest.java#L415

If this is correct, it does not seem to correctly implement the format of the Eth2.0 spec https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md#bitlistn

which specifies that the bits should be put together in Bytes (which seems to a good idea as produces more compact encodings).

Is that going to be problem when communicating with clients that do implement the spec?

**Comment by atoulme** [comment]
The current SSZ implementation fell behind the spec. It needs to update to the latest eth2 tests and adapt.

I recently added the eth2 spec tests as a submodule to allow for this, but haven't pushed for running the tests yet.

**Comment by franck44** [comment]
Thanks @atoulme 

I am interested in getting the test results when it is set up to run.

**Comment by atoulme** [comment]
I think this might be covered by https://github.com/apache/incubator-tuweni/pull/487 - closing. Please reopen if more work is needed.
