### ISSUE TITLE
FileBackedFingerprintRepository throws NPE if fingerPrintFile has no parent Dir

### ISSUE THREAD

**Issue by rain-on** [apache/incubator-tuweni#50]
When attempt to create a FileBackedFingerprintRepository, if the supplied path is a simple filename (eg Path.of("file.tmp"), it effectively has no parent directory, and thus the call to createDirectories() (on line 39) is invoked with a 'null' parameter, resulting in an NPE.

Current workaround is to ensure it the FileBackedFingerprintRepository is instantiated with an absolutePath

**Comment by atoulme** [comment]
Sure thing. Note this means the path is relative to the current Java working directory, so an absolute path is still preferred imo. I have fixed the issue with the commit above, please review.
