### ISSUE TITLE
ETH proxy

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#58]
An ETH proxy is a service running the Ethereum wire protocol, allowing one or more clients to run behind it while keeping connections open.

**Motivation**
The current peer-to-peer networking does not allow hot restarts of Ethereum clients.

We want to implement just enough logic we can keep connections open with existing peers, while we have the ability to create controller/worker or controller/controller replication schemes.

**Scope of work**
* Implement ETH proxy to capture and replay most important messages - status, in particular.
* Implement distribution of executable running ETH proxy

**Comment by abbasdgr8** [comment]
Hi @atoulme 

I wouldn't mind working on this.

**Comment by atoulme** [comment]
Go ahead, all contributions welcome!
