### ISSUE TITLE
TOML library does not seem to handle arrays.

### ISSUE THREAD

**Issue by atoulme** [apache/incubator-tuweni#65]
Migrated from https://issues.apache.org/jira/projects/TUWENI/issues/TUWENI-32

TOML parsing does not work without adding extra `'` quotes.

We get this org.apache.tuweni.toml.TomlInvalidTypeException: Value of 'plugin-kafka-log-filter-topics' is a array

This mean the following config does not work:
```
plugin-kafka-log-filter-topics = [
    [ "0xd3610b1c54575b7f4f0dc03d210b8ac55624ae007679b7a928a4f25a709331a8" ]
]
```
This is confusing for users since they don't have have to put extra quotes for the command line and they have to for the TOML config file.

Moreover this is a valid TOML configuration file without extra quotes.

More context here:

https://github.com/PegaSysEng/plus/pull/177

**Comment by schroedingerscode** [comment]
This was found to be an issue in the PegaSys/Hyperledger implementation of the IDefaultValueProvider. This was tested and found to be working in Tuweni, and the fix has been implemented in the upstream repo.
