### ISSUE TITLE
Bytes.fromByteBuf() incorrectly interpret ByteBuf content

### ISSUE THREAD

**Issue by Nashatyrev** [apache/incubator-tuweni#88]
### To reproduce
```java
    ByteBuf buf = Unpooled.buffer(100).writeByte(1);
    Bytes bytes = Bytes.wrapByteBuf(buf);
    System.out.println(bytes.size());
    System.out.println(bytes.toArray().length);
```
### Expected behavior
```
1
1
```
The `buf` content is only 1 byte, other 99 reserved bytes are not the part of the buffer content 

### Observed behavior 
```
100
100
```

**Comment by atoulme** [comment]
So I see that you go by readable bytes, and the implementation goes by capacity.

What's a good fix here? A new utility method that copies bytes out to a different buffer (as it seems like you run into issues with keeping a reference to the original ByteBuf anyway) or a fix to the class to go by readableBytes() as size?

**Comment by cleishm** [comment]
I’d say the expected output is 100. A byte buffer is not variably sized, but rather sized at creation.

**Comment by atoulme** [comment]
Yeah, I tend to agree. I mean, we could create another Bytes implementation that goes by readable bytes. I think that'd be surprising though.

**Comment by atoulme** [comment]
You can also do this:
`Bytes.wrapByteBuf(buffer, 0, buffer.readableBytes())` which will give you the right size.

Closing this issue, please feel free to reopen if there's more to this.

**Comment by Nashatyrev** [comment]
> `Bytes.wrapByteBuf(buffer, 0, buffer.readableBytes())`

The more correct usage then would be: `Bytes.wrapByteBuf(buffer, buffer.readerIndex(), buffer.readableBytes())` 

> I’d say the expected output is 100. A byte buffer is not variably sized, but rather sized at creation. Its content is 100 bytes. You just have 99 that are undefined.

I would tend to disagree here: 

```java
    ByteBuf buf = Unpooled.buffer().writeByte(1);
    Bytes bytes = Bytes.wrapByteBuf(buf);
    System.out.println(bytes.size());
```

This would output `256`. If you write `300` bytes, the output would be `512`. Another Netty version may potentially allocate other buffer size by default which makes `Bytes.wrapByteBuf()` behavior inconsistent. 

Just another sample: that would output `1`
```java
    ByteBuf buf = Unpooled.buffer().writeByte(1);
    ByteBuf wBuf = Unpooled.wrappedBuffer(buf);
    Bytes bytes = Bytes.wrapByteBuf(wBuf);
    System.out.println(bytes.size());
```

The 'true' `ByteBuf` content starts at `readerIndex` and has size `readableBytes`. While other buffer content is still available via `ByteBuf` API it should be treated as junk. When allocating buf via `Unpooled.directBuffer()` you may even potentially have uninitialized memory in the rest of the buffer. 

I see the option of `Bytes.wrapByteBuf(ByteBuf, int, int)` but I still think the method `Bytes.wrapByteBuf(ByteBuf)` default behavior should be to wrap only the readable content of `ByteBuf`. 

I would reopen the issue for the next round of discussions

**Comment by cleishm** [comment]
What you're dealing with here is the semantics of Netty's `ByteBuf`. It contains pointers for readable and writable pointers and provides a method `Unpooled.buffer()` that provides a buffer who's capacity may vary between implementations, and it doesn't guarantee bytes are zeroed out. These are not features of the `Bytes` implementation in Tuweni.

Given Netty provides methods to present just the "readable" bytes as a `ByteBuf`, e.g. `Unpooled.wrappedBuffer(byteBuf)`, I'm not sure the implementation of `Bytes.wrapByteBuffer(...)` is definitively wrong or needs to be changed, as you have the option to achieve what you're looking for via `Bytes.wrapByteBuffer(Unpooled.wrappedBuffer(...))`. That said, I'm sure @atoulme would also happily consider an alternative constructor method that inlines this behavior.

**Comment by Nashatyrev** [comment]
> These are not features of the Bytes implementation in Tuweni

And this is exactly the reason why I would expect from `Bytes` to wrap only readable `ByteBuf` content

> Given Netty provides methods to present just the "readable" bytes as a ByteBuf, e.g. `Unpooled.wrappedBuffer(byteBuf)`

`Unpooled.wrappedBuffer(byteBuf)` is actually was just an example. It is normally used to 'concat' several `ButeBuf`s. And it concats only readable bytes. 

It is absolutely regular use case for Netty to receive a wire frame in a `ByteBuf` e.g. `| header | payload |` and then a lower-level decoder reads the header and then passes the same `ByteBuf` to a higher-level decoder with a `readerIndex` positioned to the beginning of  `| payload |` and the higher-level decoder treat that `ByteBuf` exactly as just only `| payload |`. 
So in that case I would expect `Bytes.wrapByteBuf()` to return only payload bytes.

You may also check Google results on ["netty bytebuf to array"](https://www.google.com/search?client=firefox-b-d&q=netty+bytebuf+to+array)

If you think the existing behavior is the one which is expected (or may be already relied on by other libs), I would add a Javadoc comment and and an alternative method which wraps the `ByteBuf` readable contents only.

**Comment by Nashatyrev** [comment]
> If you think the existing behavior is the one which is expected (or may be already relied on by other libs), I would add a Javadoc comment and and an alternative method which wraps the ByteBuf readable contents only.

Hey, I would still suggest to address this issue in one or another way. It's definitely not a showstopper, but I'm pretty sure there would definitely be misreading and erroneous usage of this method in the future.

**Comment by atoulme** [comment]
I think the project would welcome a contribution to address this feature gap and confusion. Closing for now as it has been a little while.
